# Generated by Django 5.1.6 on 2026-03-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideposting', '0002_alter_ride_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='drop_off_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_off_lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_off_lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pick_up_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pick_up_lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pick_up_lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
