# Generated by Django 4.2.25 on 2026-04-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideposting', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Ride',
            new_name='ride',
        ),
    ]
