# Generated by Django 4.2.25 on 2026-04-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideposting', '0003_alter_message_options_rename_ride_message_ride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time']},
        ),
    ]
