# Generated by Django 6.0.1 on 2026-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideposting', '0003_ride_drop_off_id_ride_drop_off_lat_ride_drop_off_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='drop_off_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='drop_off_lat',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='drop_off_lng',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pick_up_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pick_up_lat',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pick_up_lng',
        ),
        migrations.AddField(
            model_name='ride',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
