# Generated by Django 5.1.6 on 2026-03-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideposting', '0003_ride_drop_off_id_ride_drop_off_lat_ride_drop_off_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
