# Generated by Django 5.1.6 on 2026-03-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideposting', '0004_ride_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='drop_off_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='drop_off_lat',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='drop_off_lng',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pick_up_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pick_up_lat',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pick_up_lng',
        ),
    ]
