# Generated by Django 6.0.1 on 2026-03-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideposting', '0004_remove_ride_drop_off_id_remove_ride_drop_off_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='time',
            new_name='pick_up_time',
        ),
    ]
