# Generated by Django 6.0.2 on 2026-02-27 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='email_address',
        ),
    ]
