# Generated by Django 6.0.2 on 2026-02-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_rename_email_profile_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lname',
        ),
    ]
